export const LAW_SCHOOLS = [
  "Nigerian Law School - Lagos",
  "Nigerian Law School - Abuja",
  "Nigerian Law School - Enugu",
  "Nigerian Law School - Bayelsa",
  "Nigerian Law School - Kano",
  "Nigerian Law School - Yola",
];

export const UNDERGRAD_INSTITUTIONS = [
  "Abia State University",
  "Ahmadu Bello University (ABU)",
  "Afe Babalola University",
  "Bayero University Kano (BUK)",
  "Benue State University",
  "Bingham University",
  "Covenant University",
  "Federal University of Technology (FUTO)",
  "Nile University",
  "Obafemi Awolowo University (OAU)",
  "Redeemer's University",
  "University of Abuja",
  "University of Benin (UNIBEN)",
  "University of Calabar (UNICAL)",
  "University of Ibadan (UI)",
  "University of Ilorin (UNILORIN)",
  "University of Jos",
  "University of Lagos (UNILAG)",
  "University of Maiduguri",
  "University of Nigeria (UNN)",
  "University of Port Harcourt (UNIPORT)",
  "Other",
];
