export const LAW_SCHOOLS = [
  "Nigerian Law School",
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "University of Benin (UNIBEN)",
  "Ahmadu Bello University (ABU)",
  "University of Nigeria (UNN)",
  "Obafemi Awolowo University (OAU)",
  "University of Port Harcourt (UNIPORT)",
  "Bayero University Kano (BUK)",
  "University of Ilorin (UNILORIN)",
  "University of Calabar (UNICAL)",
  "Afe Babalola University",
  "Nile University",
  "Covenant University",
  "Redeemer's University",
  "University of Abuja",
  "Benue State University",
  "University of Jos",
  "Federal University of Technology (FUTO)",
  "Abia State University",
  "Other"
];

export const UNDERGRAD_INSTITUTIONS = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "University of Benin (UNIBEN)",
  "Ahmadu Bello University (ABU)",
  "University of Nigeria (UNN)",
  "Obafemi Awolowo University (OAU)",
  "University of Port Harcourt (UNIPORT)",
  "Bayero University Kano (BUK)",
  "University of Ilorin (UNILORIN)",
  "University of Calabar (UNICAL)",
  "Afe Babalola University",
  "Nile University",
  "Covenant University",
  "Redeemer's University",
  "Bingham University",
  "University of Abuja",
  "Benue State University",
  "University of Jos",
  "University of Maiduguri",
  "Abia State University",
];
